version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=roomCounter
      # - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
