kumuluzee:
  name: prpo-s01-api
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/roomCounterDS
      connection-url: jdbc:postgresql://postgres:5432/roomCounter
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: both
        jndi-name: jdbc/roomCounterDS
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi
    ui:
      mapping: /openapi/ui
intergations:
  history-system:
    base-url: http://localhost:8081/v1
