kumuluzee:
  name: prpo-s01-api
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/roomCounterDS
      connection-url: jdbc:postgresql://postgres:5432/roomCounter
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: both
        jndi-name: jdbc/roomCounterDS
      disk-space-health-check:
        threshold: 100000000
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi
    ui:
      mapping: /openapi/ui
  dev:
    scan-libraries:
      - entities
      - services
  integrations:
    history-system:
      base-url: http://history:8080/v1
  security:
    keycloak:
      json: '{
               "realm": "counter-realm",
               "bearer-only": true,
               "auth-server-url": "http://localhost:8082/auth/",
               "ssl-required": "external",
               "resource": "counter-api",
               "confidential-port": 0
             }'
  kumuluzee:
    cors-filter:
      servlet:
        allow-generic-http-requests: false
        allow-origin: "*"
