kumuluzee:
  name: prpo-s01-api
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/roomCounterDS
      connection-url: jdbc:postgresql://localhost:5433/roomCounter
      username: postgres
      password: postgres
      max-pool-size: 20
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi
    ui:
      mapping: /openapi/ui